version: "3.9"

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-db
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: oracle123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "ls", "/opt/oracle/oradata"]
      interval: 30s
      timeout: 10s
      retries: 10

  python-oracle-app:
    image: projectaws/python_oracle
    container_name: python-oracle-app
    depends_on:
      oracle-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data/output:/app/data/output
    environment:
      - HOSTNAME=oracle-db
      - PORT=1521
      - SERVICE_NAME=ORCLPDB1

volumes:
  oracle-data:
