apiVersion: v1
kind: Secret
metadata:
  name: oracle-db-secret
type: Opaque
stringData:
  ORACLE_USER: admin
  ORACLE_PASSWORD: oracle123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
        - name: oracle-db
          image: container-registry.oracle.com/database/enterprise:19.3.0.0
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_SID
              value: ORCLCDB
            - name: ORACLE_PDB
              value: ORCLPDB1
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: oracle-db-secret
                  key: ORACLE_PASSWORD
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oracle-data
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
spec:
  type: ClusterIP
  selector:
    app: oracle-db
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
