FROM python:3.10

# Set working directory inside the container
WORKDIR /app

# Copy your app code and requirements file into the container
COPY app.py /app/
COPY requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Command to run the app
CMD ["python", "app.py"]

