apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: tdk-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: projectaws/schedule_service
        envFrom:
        - secretRef:
            name: oracle-secret
