apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: tdk-devops
type: Opaque
stringData:
  ORACLE_USER: system
  ORACLE_PASSWORD: oracle
  ORACLE_DSN: oracle-db.tdk-devops.svc.cluster.local/XEPDB1
  DATA_PATH: /data/output.tsv
